/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mraih
 */
public class PaymentMethod extends javax.swing.JFrame {

    /**
     * Creates new form paymentMethod
     */
    public PaymentMethod() {
        initComponents();
        panelOption.setVisible(false);
        buttonBuy.setVisible(false);
        labelHarga.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBoxOption = new javax.swing.JComboBox<>();
        panelOption = new javax.swing.JPanel();
        radioButton1 = new javax.swing.JRadioButton();
        radioButton2 = new javax.swing.JRadioButton();
        radioButton3 = new javax.swing.JRadioButton();
        radioButton4 = new javax.swing.JRadioButton();
        radioButton5 = new javax.swing.JRadioButton();
        buttonBuy = new javax.swing.JButton();
        labelHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setForeground(new java.awt.Color(0, 102, 51));

        comboBoxOption.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Transfer Bank (VA Account)", "Gerai" }));
        comboBoxOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxOptionActionPerformed(evt);
            }
        });

        panelOption.setBackground(new java.awt.Color(0, 59, 29));

        radioButton1.setForeground(new java.awt.Color(255, 255, 255));
        radioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton1ActionPerformed(evt);
            }
        });

        radioButton2.setForeground(new java.awt.Color(255, 255, 255));
        radioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton2ActionPerformed(evt);
            }
        });

        radioButton3.setForeground(new java.awt.Color(255, 255, 255));
        radioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton3ActionPerformed(evt);
            }
        });

        radioButton4.setForeground(new java.awt.Color(255, 255, 255));
        radioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton4ActionPerformed(evt);
            }
        });

        radioButton5.setForeground(new java.awt.Color(255, 255, 255));
        radioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOptionLayout = new javax.swing.GroupLayout(panelOption);
        panelOption.setLayout(panelOptionLayout);
        panelOptionLayout.setHorizontalGroup(
            panelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButton1)
                    .addComponent(radioButton2)
                    .addComponent(radioButton3)
                    .addComponent(radioButton4)
                    .addComponent(radioButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOptionLayout.setVerticalGroup(
            panelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButton5)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        buttonBuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonBuy.setText("BAYAR");
        buttonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuyActionPerformed(evt);
            }
        });

        labelHarga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelHarga.setForeground(new java.awt.Color(255, 255, 255));
        labelHarga.setText("Total : Rp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHarga)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxOption, 0, 330, Short.MAX_VALUE)
                        .addComponent(buttonBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(labelHarga)
                .addGap(18, 18, 18)
                .addComponent(buttonBuy)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxOptionActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String) comboBoxOption.getSelectedItem();
        if (selectedOption.equals("Transfer Bank (VA Account)")) {
            panelOption.setVisible(true);
            radioButton1.setVisible(true);
            radioButton1.setText("BCA");
            radioButton2.setVisible(true);
            radioButton2.setText("Mandiri");
            radioButton3.setVisible(true);
            radioButton3.setText("BNI");
            radioButton4.setVisible(true);
            radioButton4.setText("BRI");
            radioButton5.setVisible(false);
            labelHarga.setVisible(true);
            buttonBuy.setVisible(true);
        } else if (selectedOption.equals("Gerai")) {
            panelOption.setVisible(true);
            radioButton1.setVisible(true);
            radioButton1.setText("Alfamart");
            radioButton2.setVisible(false);
            radioButton3.setVisible(true);
            radioButton3.setText("Indomaret");
            radioButton4.setVisible(false);
            radioButton5.setVisible(true);
            radioButton5.setText("Kantor Pos");
            labelHarga.setVisible(true);
            buttonBuy.setVisible(true);
        } else {
            panelOption.setVisible(false);
            buttonBuy.setVisible(false);
        }
    }//GEN-LAST:event_comboBoxOptionActionPerformed

    private void radioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton1ActionPerformed
        // TODO add your handling code here:
        if (radioButton1.isSelected()) {

            radioButton2.setSelected(false);
            radioButton3.setSelected(false);
            radioButton4.setSelected(false);
            radioButton5.setSelected(false);
        }
    }//GEN-LAST:event_radioButton1ActionPerformed

    private void radioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton2ActionPerformed
        // TODO add your handling code here:
        if (radioButton2.isSelected()) {
            radioButton1.setSelected(false);
            radioButton3.setSelected(false);
            radioButton4.setSelected(false);
            radioButton5.setSelected(false);
        }
    }//GEN-LAST:event_radioButton2ActionPerformed

    private void radioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton3ActionPerformed
        // TODO add your handling code here:
        if (radioButton3.isSelected()) {
            radioButton1.setSelected(false);
            radioButton2.setSelected(false);
            radioButton4.setSelected(false);
            radioButton5.setSelected(false);
        }
    }//GEN-LAST:event_radioButton3ActionPerformed

    private void radioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton4ActionPerformed
        // TODO add your handling code here:
        if (radioButton4.isSelected()) {
            radioButton1.setSelected(false);
            radioButton3.setSelected(false);
            radioButton2.setSelected(false);
            radioButton5.setSelected(false);
        }
    }//GEN-LAST:event_radioButton4ActionPerformed

    private void radioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton5ActionPerformed
        // TODO add your handling code here:
        if (radioButton5.isSelected()) {
            radioButton1.setSelected(false);
            radioButton3.setSelected(false);
            radioButton4.setSelected(false);
            radioButton2.setSelected(false);
        }
    }//GEN-LAST:event_radioButton5ActionPerformed

    private void buttonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuyActionPerformed
        // TODO add your handling code here:
        Payment pay = new Payment();
        pay.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentMethod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuy;
    private javax.swing.JComboBox<String> comboBoxOption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JPanel panelOption;
    private javax.swing.JRadioButton radioButton1;
    private javax.swing.JRadioButton radioButton2;
    private javax.swing.JRadioButton radioButton3;
    private javax.swing.JRadioButton radioButton4;
    private javax.swing.JRadioButton radioButton5;
    // End of variables declaration//GEN-END:variables
}
