/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mraih
 */
public class PickTrainSeat extends javax.swing.JFrame {

    /**
     * Creates new form PickTrainSeat
     */
    public PickTrainSeat() {
        initComponents();
        panelEconomic.setVisible(false);
        panelEksekutif.setVisible(true);
        setSize(279,630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEconomic = new javax.swing.JPanel();
        seatA1 = new javax.swing.JToggleButton();
        seatB1 = new javax.swing.JToggleButton();
        seatC1 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        seatB2 = new javax.swing.JToggleButton();
        seatC2 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        seatA2 = new javax.swing.JToggleButton();
        seatB3 = new javax.swing.JToggleButton();
        seatC3 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        seatA3 = new javax.swing.JToggleButton();
        seatB4 = new javax.swing.JToggleButton();
        seatC4 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        seatA4 = new javax.swing.JToggleButton();
        seatB5 = new javax.swing.JToggleButton();
        seatC5 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        seatA5 = new javax.swing.JToggleButton();
        seatB6 = new javax.swing.JToggleButton();
        seatC6 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        seatA6 = new javax.swing.JToggleButton();
        seatB7 = new javax.swing.JToggleButton();
        seatB8 = new javax.swing.JToggleButton();
        seatC7 = new javax.swing.JToggleButton();
        seatC8 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        seatA7 = new javax.swing.JToggleButton();
        seatA8 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        panelEksekutif = new javax.swing.JPanel();
        seatA9 = new javax.swing.JToggleButton();
        seatB9 = new javax.swing.JToggleButton();
        seatC9 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton18 = new javax.swing.JToggleButton();
        seatC10 = new javax.swing.JToggleButton();
        seatB10 = new javax.swing.JToggleButton();
        seatA10 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        seatC11 = new javax.swing.JToggleButton();
        seatB11 = new javax.swing.JToggleButton();
        seatA11 = new javax.swing.JToggleButton();
        seatA12 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        seatB12 = new javax.swing.JToggleButton();
        seatC12 = new javax.swing.JToggleButton();
        seatC13 = new javax.swing.JToggleButton();
        seatA13 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        seatB13 = new javax.swing.JToggleButton();
        seatC14 = new javax.swing.JToggleButton();
        seatB14 = new javax.swing.JToggleButton();
        seatA14 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 51));
        setResizable(false);

        panelEconomic.setBackground(new java.awt.Color(0, 59, 29));

        seatA1.setText("A1");
        seatA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA1ActionPerformed(evt);
            }
        });

        seatB1.setText("B1");
        seatB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB1ActionPerformed(evt);
            }
        });

        seatC1.setText("C1");
        seatC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC1ActionPerformed(evt);
            }
        });

        jToggleButton9.setText("D1");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        seatB2.setText("B2");
        seatB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB2ActionPerformed(evt);
            }
        });

        seatC2.setText("C2");
        seatC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC2ActionPerformed(evt);
            }
        });

        jToggleButton10.setText("D2");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        seatA2.setText("A2");
        seatA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA2ActionPerformed(evt);
            }
        });

        seatB3.setText("B3");
        seatB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB3ActionPerformed(evt);
            }
        });

        seatC3.setText("C3");
        seatC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC3ActionPerformed(evt);
            }
        });

        jToggleButton11.setText("D3");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });

        seatA3.setText("A3");
        seatA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA3ActionPerformed(evt);
            }
        });

        seatB4.setText("B4");
        seatB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB4ActionPerformed(evt);
            }
        });

        seatC4.setText("C4");
        seatC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC4ActionPerformed(evt);
            }
        });

        jToggleButton12.setText("D4");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });

        seatA4.setText("A4");
        seatA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA4ActionPerformed(evt);
            }
        });

        seatB5.setText("B5");
        seatB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB5ActionPerformed(evt);
            }
        });

        seatC5.setText("C5");
        seatC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC5ActionPerformed(evt);
            }
        });

        jToggleButton13.setText("D5");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        seatA5.setText("A5");
        seatA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA5ActionPerformed(evt);
            }
        });

        seatB6.setText("B7");
        seatB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB6ActionPerformed(evt);
            }
        });

        seatC6.setText("C7");
        seatC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC6ActionPerformed(evt);
            }
        });

        jToggleButton14.setText("D7");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        seatA6.setText("A7");
        seatA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA6ActionPerformed(evt);
            }
        });

        seatB7.setText("B8");
        seatB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB7ActionPerformed(evt);
            }
        });

        seatB8.setText("B6");
        seatB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB8ActionPerformed(evt);
            }
        });

        seatC7.setText("C8");
        seatC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC7ActionPerformed(evt);
            }
        });

        seatC8.setText("C6");
        seatC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC8ActionPerformed(evt);
            }
        });

        jToggleButton15.setText("D8");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        jToggleButton16.setText("D6");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        seatA7.setText("A8");
        seatA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA7ActionPerformed(evt);
            }
        });

        seatA8.setText("A6");
        seatA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kelas Ekonomi");

        javax.swing.GroupLayout panelEconomicLayout = new javax.swing.GroupLayout(panelEconomic);
        panelEconomic.setLayout(panelEconomicLayout);
        panelEconomicLayout.setHorizontalGroup(
            panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEconomicLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEconomicLayout.createSequentialGroup()
                        .addComponent(seatA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB1)
                        .addGap(60, 60, 60)
                        .addComponent(seatC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton9))
                    .addGroup(panelEconomicLayout.createSequentialGroup()
                        .addComponent(seatA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB2)
                        .addGap(60, 60, 60)
                        .addComponent(seatC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton10))
                    .addGroup(panelEconomicLayout.createSequentialGroup()
                        .addComponent(seatA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB3)
                        .addGap(60, 60, 60)
                        .addComponent(seatC3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton11))
                    .addGroup(panelEconomicLayout.createSequentialGroup()
                        .addComponent(seatA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB4)
                        .addGap(60, 60, 60)
                        .addComponent(seatC4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton12))
                    .addGroup(panelEconomicLayout.createSequentialGroup()
                        .addComponent(seatA5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB5)
                        .addGap(60, 60, 60)
                        .addComponent(seatC5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton13))
                    .addGroup(panelEconomicLayout.createSequentialGroup()
                        .addComponent(seatA6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB6)
                        .addGap(60, 60, 60)
                        .addComponent(seatC6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton14))
                    .addGroup(panelEconomicLayout.createSequentialGroup()
                        .addComponent(seatA7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB7)
                        .addGap(60, 60, 60)
                        .addComponent(seatC7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton15))
                    .addGroup(panelEconomicLayout.createSequentialGroup()
                        .addComponent(seatA8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB8)
                        .addGap(60, 60, 60)
                        .addComponent(seatC8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEconomicLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        panelEconomicLayout.setVerticalGroup(
            panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEconomicLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEconomicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelEksekutif.setBackground(new java.awt.Color(0, 59, 29));
        panelEksekutif.setForeground(new java.awt.Color(225, 225, 225));

        seatA9.setText("A1");
        seatA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA9ActionPerformed(evt);
            }
        });

        seatB9.setText("B1");
        seatB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB9ActionPerformed(evt);
            }
        });

        seatC9.setText("C1");
        seatC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC9ActionPerformed(evt);
            }
        });

        jToggleButton17.setText("D1");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelas Eksekutif");

        jToggleButton18.setText("D1");
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });

        seatC10.setText("C1");
        seatC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC10ActionPerformed(evt);
            }
        });

        seatB10.setText("B1");
        seatB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB10ActionPerformed(evt);
            }
        });

        seatA10.setText("A1");
        seatA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA10ActionPerformed(evt);
            }
        });

        jToggleButton19.setText("D1");
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });

        seatC11.setText("C1");
        seatC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC11ActionPerformed(evt);
            }
        });

        seatB11.setText("B1");
        seatB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB11ActionPerformed(evt);
            }
        });

        seatA11.setText("A1");
        seatA11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA11ActionPerformed(evt);
            }
        });

        seatA12.setText("A1");
        seatA12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA12ActionPerformed(evt);
            }
        });

        jToggleButton20.setText("D1");
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });

        seatB12.setText("B1");
        seatB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB12ActionPerformed(evt);
            }
        });

        seatC12.setText("C1");
        seatC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC12ActionPerformed(evt);
            }
        });

        seatC13.setText("C1");
        seatC13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC13ActionPerformed(evt);
            }
        });

        seatA13.setText("A1");
        seatA13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA13ActionPerformed(evt);
            }
        });

        jToggleButton21.setText("D1");
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });

        seatB13.setText("B1");
        seatB13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB13ActionPerformed(evt);
            }
        });

        seatC14.setText("C1");
        seatC14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatC14ActionPerformed(evt);
            }
        });

        seatB14.setText("B1");
        seatB14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatB14ActionPerformed(evt);
            }
        });

        seatA14.setText("A1");
        seatA14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA14ActionPerformed(evt);
            }
        });

        jToggleButton22.setText("D1");
        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEksekutifLayout = new javax.swing.GroupLayout(panelEksekutif);
        panelEksekutif.setLayout(panelEksekutifLayout);
        panelEksekutifLayout.setHorizontalGroup(
            panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEksekutifLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(seatA9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatB9)
                .addGap(60, 60, 60)
                .addComponent(seatC9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEksekutifLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEksekutifLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEksekutifLayout.createSequentialGroup()
                        .addComponent(seatA10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatB10)
                        .addGap(60, 60, 60)
                        .addComponent(seatC10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton18)
                        .addContainerGap())
                    .addGroup(panelEksekutifLayout.createSequentialGroup()
                        .addGroup(panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEksekutifLayout.createSequentialGroup()
                                .addComponent(seatA11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatB11)
                                .addGap(60, 60, 60)
                                .addComponent(seatC11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton19))
                            .addGroup(panelEksekutifLayout.createSequentialGroup()
                                .addComponent(seatA12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatB12)
                                .addGap(60, 60, 60)
                                .addComponent(seatC12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton20))
                            .addGroup(panelEksekutifLayout.createSequentialGroup()
                                .addComponent(seatA13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatB13)
                                .addGap(60, 60, 60)
                                .addComponent(seatC13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton21))
                            .addGroup(panelEksekutifLayout.createSequentialGroup()
                                .addComponent(seatA14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatB14)
                                .addGap(60, 60, 60)
                                .addComponent(seatC14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton22)))
                        .addContainerGap())))
        );
        panelEksekutifLayout.setVerticalGroup(
            panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEksekutifLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelEksekutifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEconomic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEksekutif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEconomic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEksekutif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seatA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA1ActionPerformed

    private void seatB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB1ActionPerformed

    private void seatC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC1ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void seatB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB2ActionPerformed

    private void seatC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC2ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void seatA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA2ActionPerformed

    private void seatB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB3ActionPerformed

    private void seatC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC3ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void seatA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA3ActionPerformed

    private void seatB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB4ActionPerformed

    private void seatC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC4ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void seatA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA4ActionPerformed

    private void seatB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB5ActionPerformed

    private void seatC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC5ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void seatA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA5ActionPerformed

    private void seatB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB6ActionPerformed

    private void seatC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC6ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void seatA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA6ActionPerformed

    private void seatB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB7ActionPerformed

    private void seatB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB8ActionPerformed

    private void seatC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC7ActionPerformed

    private void seatC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC8ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void seatA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA7ActionPerformed

    private void seatA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA8ActionPerformed

    private void seatA9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA9ActionPerformed

    private void seatB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB9ActionPerformed

    private void seatC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC9ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void seatC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC10ActionPerformed

    private void seatB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB10ActionPerformed

    private void seatA10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA10ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void seatC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC11ActionPerformed

    private void seatB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB11ActionPerformed

    private void seatA11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA11ActionPerformed

    private void seatA12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA12ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void seatB12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB12ActionPerformed

    private void seatC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC12ActionPerformed

    private void seatC13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC13ActionPerformed

    private void seatA13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA13ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void seatB13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB13ActionPerformed

    private void seatC14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatC14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatC14ActionPerformed

    private void seatB14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatB14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatB14ActionPerformed

    private void seatA14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA14ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickTrainSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickTrainSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickTrainSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickTrainSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickTrainSeat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JPanel panelEconomic;
    private javax.swing.JPanel panelEksekutif;
    private javax.swing.JToggleButton seatA1;
    private javax.swing.JToggleButton seatA10;
    private javax.swing.JToggleButton seatA11;
    private javax.swing.JToggleButton seatA12;
    private javax.swing.JToggleButton seatA13;
    private javax.swing.JToggleButton seatA14;
    private javax.swing.JToggleButton seatA2;
    private javax.swing.JToggleButton seatA3;
    private javax.swing.JToggleButton seatA4;
    private javax.swing.JToggleButton seatA5;
    private javax.swing.JToggleButton seatA6;
    private javax.swing.JToggleButton seatA7;
    private javax.swing.JToggleButton seatA8;
    private javax.swing.JToggleButton seatA9;
    private javax.swing.JToggleButton seatB1;
    private javax.swing.JToggleButton seatB10;
    private javax.swing.JToggleButton seatB11;
    private javax.swing.JToggleButton seatB12;
    private javax.swing.JToggleButton seatB13;
    private javax.swing.JToggleButton seatB14;
    private javax.swing.JToggleButton seatB2;
    private javax.swing.JToggleButton seatB3;
    private javax.swing.JToggleButton seatB4;
    private javax.swing.JToggleButton seatB5;
    private javax.swing.JToggleButton seatB6;
    private javax.swing.JToggleButton seatB7;
    private javax.swing.JToggleButton seatB8;
    private javax.swing.JToggleButton seatB9;
    private javax.swing.JToggleButton seatC1;
    private javax.swing.JToggleButton seatC10;
    private javax.swing.JToggleButton seatC11;
    private javax.swing.JToggleButton seatC12;
    private javax.swing.JToggleButton seatC13;
    private javax.swing.JToggleButton seatC14;
    private javax.swing.JToggleButton seatC2;
    private javax.swing.JToggleButton seatC3;
    private javax.swing.JToggleButton seatC4;
    private javax.swing.JToggleButton seatC5;
    private javax.swing.JToggleButton seatC6;
    private javax.swing.JToggleButton seatC7;
    private javax.swing.JToggleButton seatC8;
    private javax.swing.JToggleButton seatC9;
    // End of variables declaration//GEN-END:variables
}
