/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mraih
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        labelKodePemesanan = new javax.swing.JLabel();
        kodePemesanan = new javax.swing.JLabel();
        ticket = new javax.swing.JPanel();
        jamBerangkat = new javax.swing.JLabel();
        jamTiba = new javax.swing.JLabel();
        tanggalBerangkat = new javax.swing.JLabel();
        tanggalTiba = new javax.swing.JLabel();
        stasiunAwal = new javax.swing.JLabel();
        stasiunAkhir = new javax.swing.JLabel();
        namaKereta = new javax.swing.JLabel();
        labelPenumpang = new javax.swing.JLabel();
        namaPenumpang1 = new javax.swing.JLabel();
        jenisID1 = new javax.swing.JLabel();
        jenisID2 = new javax.swing.JLabel();
        namaPenumpang2 = new javax.swing.JLabel();
        namaPenumpang3 = new javax.swing.JLabel();
        jenisID3 = new javax.swing.JLabel();
        namaPenumpang4 = new javax.swing.JLabel();
        jenisID4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 102, 51));

        header.setBackground(new java.awt.Color(255, 255, 255));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo KYI.png"))); // NOI18N

        labelKodePemesanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelKodePemesanan.setForeground(new java.awt.Color(0, 0, 0));
        labelKodePemesanan.setText("Kode Pemesanan");

        kodePemesanan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        kodePemesanan.setForeground(new java.awt.Color(0, 0, 0));
        kodePemesanan.setText("########");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LOGO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(labelKodePemesanan)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(kodePemesanan)
                        .addGap(29, 29, 29))))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGO, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelKodePemesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodePemesanan))
        );

        ticket.setBackground(new java.awt.Color(0, 59, 29));

        jamBerangkat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jamBerangkat.setForeground(new java.awt.Color(255, 255, 255));
        jamBerangkat.setText("Jam B");

        jamTiba.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jamTiba.setForeground(new java.awt.Color(255, 255, 255));
        jamTiba.setText("Jam B");

        tanggalBerangkat.setForeground(new java.awt.Color(255, 255, 255));
        tanggalBerangkat.setText("Tanggal");

        tanggalTiba.setForeground(new java.awt.Color(255, 255, 255));
        tanggalTiba.setText("Tanggal");

        stasiunAwal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stasiunAwal.setForeground(new java.awt.Color(255, 255, 255));
        stasiunAwal.setText("STASIUN AWAL");

        stasiunAkhir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stasiunAkhir.setForeground(new java.awt.Color(255, 255, 255));
        stasiunAkhir.setText("STASIUN AKHIR");

        namaKereta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        namaKereta.setForeground(new java.awt.Color(255, 255, 255));
        namaKereta.setText("NAMA KERETA");

        javax.swing.GroupLayout ticketLayout = new javax.swing.GroupLayout(ticket);
        ticket.setLayout(ticketLayout);
        ticketLayout.setHorizontalGroup(
            ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalBerangkat)
                    .addComponent(jamBerangkat)
                    .addComponent(tanggalTiba)
                    .addComponent(jamTiba))
                .addGap(101, 101, 101)
                .addGroup(ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stasiunAkhir)
                    .addComponent(stasiunAwal)
                    .addGroup(ticketLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(namaKereta)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        ticketLayout.setVerticalGroup(
            ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketLayout.createSequentialGroup()
                .addGroup(ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ticketLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jamBerangkat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalBerangkat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jamTiba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalTiba))
                    .addGroup(ticketLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(stasiunAwal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(namaKereta)
                        .addGap(33, 33, 33)
                        .addComponent(stasiunAkhir)))
                .addGap(11, 11, 11))
        );

        labelPenumpang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPenumpang.setForeground(new java.awt.Color(255, 255, 255));
        labelPenumpang.setText("Penumpang");

        namaPenumpang1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namaPenumpang1.setForeground(new java.awt.Color(255, 255, 255));
        namaPenumpang1.setText("Nama Penumpang");

        jenisID1.setForeground(new java.awt.Color(255, 255, 255));
        jenisID1.setText("Jenis ID - Nomor ID");

        jenisID2.setForeground(new java.awt.Color(255, 255, 255));
        jenisID2.setText("Jenis ID - Nomor ID");

        namaPenumpang2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namaPenumpang2.setForeground(new java.awt.Color(255, 255, 255));
        namaPenumpang2.setText("Nama Penumpang");

        namaPenumpang3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namaPenumpang3.setForeground(new java.awt.Color(255, 255, 255));
        namaPenumpang3.setText("Dewasa");

        jenisID3.setForeground(new java.awt.Color(255, 255, 255));
        jenisID3.setText("Tipe Tike - No Kursi");

        namaPenumpang4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namaPenumpang4.setForeground(new java.awt.Color(255, 255, 255));
        namaPenumpang4.setText("Dewasa");

        jenisID4.setForeground(new java.awt.Color(255, 255, 255));
        jenisID4.setText("Tipe Tike - No Kursi");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(labelPenumpang)
                .addGap(250, 250, 250))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addComponent(jenisID1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jenisID3))
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addComponent(namaPenumpang1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaPenumpang3))
                        .addComponent(ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenisID2)
                            .addComponent(namaPenumpang2))
                        .addGap(291, 291, 291)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jenisID4)
                            .addComponent(namaPenumpang4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPenumpang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPenumpang1)
                    .addComponent(namaPenumpang3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisID1)
                    .addComponent(jenisID3))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(namaPenumpang2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenisID2))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(namaPenumpang4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenisID4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu_KYI menu = new MainMenu_KYI();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel background;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jamBerangkat;
    private javax.swing.JLabel jamTiba;
    private javax.swing.JLabel jenisID1;
    private javax.swing.JLabel jenisID2;
    private javax.swing.JLabel jenisID3;
    private javax.swing.JLabel jenisID4;
    private javax.swing.JLabel kodePemesanan;
    private javax.swing.JLabel labelKodePemesanan;
    private javax.swing.JLabel labelPenumpang;
    private javax.swing.JLabel namaKereta;
    private javax.swing.JLabel namaPenumpang1;
    private javax.swing.JLabel namaPenumpang2;
    private javax.swing.JLabel namaPenumpang3;
    private javax.swing.JLabel namaPenumpang4;
    private javax.swing.JLabel stasiunAkhir;
    private javax.swing.JLabel stasiunAwal;
    private javax.swing.JLabel tanggalBerangkat;
    private javax.swing.JLabel tanggalTiba;
    private javax.swing.JPanel ticket;
    // End of variables declaration//GEN-END:variables
}
